displayName=Scythe Crush Warning
author=gtjamesa
description=Show a warning if your Scythe/SRA is on crush
tags=scythe,sra,soulreaper,crush,araxxor,nightmare,hueycoatl,cerberus,royal titans,amoxliatl,maggot king
plugins=com.scythecrushwarning.ScytheCrushWarningPlugin
build=standard
version=1.5.5
